FROM python:3.10-slim AS builder
WORKDIR /app
COPY requirements.txt ./
RUN pip wheel --no-cache-dir --wheel-dir /wheels -r requirements.txt

# Utiliser une image Python qui inclut pip
FROM python:3.10-slim
WORKDIR /app
COPY --from=builder /wheels /wheels
COPY app.py ./
RUN pip install /wheels/*
# Créer un utilisateur non-root
RUN useradd -u 1001 app && chown -R app /app
USER app
CMD ["python", "app.py"]
